### PR TITLE
Collection of Small Fixes: Developer Section, Image Swaps/Optimizations/Cleanups

### LINKED ISSUE #80: Bug: Developer Section at 1304px wide goes off screen
Looks like the box around the text is fixed width and the image isn't scaling instead?

Developer advantages text box is cut off

Browser: Firefox on Mac

Taken at 1304x1479:
Image

### PR DESCRIPTION
**Pull request by wilwade**
# Description

- Closes #80 
- Part of #57 

## Screenshot(s)

- Updated people's bid svg
    -  image
- Fixed issue with developers getting pushed off screen
    - image
- Optimized some images
- Renamed a generic svg
- Switched aboutRoad to a jpg for size due to the style

### CODE REVIEW

File: src/components/HAccordion.svelte [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <script lang="ts">
   import { createEventDispatcher, type Snippet } from 'svelte';
   import { Button } from '@frequency-chain/style-guide';
-  import Vector from '../lib/assets/Vector.svg';
+  import Arrow from '../lib/assets/arrow-right.svg';
```
Comment (wilwade) [inline src/components/HAccordion.svelte:4]: Rename for clarity

**Review by aramikm — APPROVED** [review]
